Descriptor:
  Name: ContosoComputersJava
  DisplayName: Contoso Computers (Java)
  Description: Find information about device health and warranties for devices from Contoso Computers and answer questions on how to resolve issues with Contoso devices.
  DescriptionsDisplay: Access information from Contoso Computers
  Icon: https://learn.microsoft.com/en-us/microsoft-365/media/contoso-overview/contoso-icon.png?view=o365-worldwide

SkillGroups:
  - Format: API
    Settings:
      OpenApiSpecUrl: https://kpwjjpfn.usw2.devtunnels.ms:8080/v3/api-docs
      EndpointUrl: https://kpwjjpfn.usw2.devtunnels.ms:8080